/* AUTHENTICATION */

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GET_PREF = 'AUTH_GET_PREF';
export const AUTH_GET_PREF_SUCCESS = 'AUTH_GET_PREF_SUCCESS';
export const AUTH_GET_PREF_FAILURE = 'AUTH_GET_PREF_FAILURE';

export const AUTH_EDIT_PREF = 'AUTH_EDIT_PREF';
export const AUTH_EDIT_PREF_SUCCESS = 'AUTH_EDIT_PREF_SUCCESS';
export const AUTH_EDIT_PREF_FAILURE = 'AUTH_EDIT_PREF_FAILURE';

export const AUTH_GET_PROFILE = 'AUTH_GET_PROFILE';
export const AUTH_GET_PROFILE_SUCCESS = 'AUTH_GET_PROFILE_SUCCESS';
export const AUTH_GET_PROFILE_FAILURE = 'AUTH_GET_PROFILE_FAILURE';

export const AUTH_EDIT_PROFILE = 'AUTH_EDIT_PROFILE';
export const AUTH_EDIT_PROFILE_SUCCESS = 'AUTH_EDIT_PROFILE_SUCCESS';
export const AUTH_EDIT_PROFILE_FAILURE = 'AUTH_EDIT_PROFILE_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/* EVENT */
export const EVENT_POST = 'EVENT_POST';
export const EVENT_POST_SUCCESS = 'EVENT_POST_SUCCESS';
export const EVENT_POST_FAILURE = 'EVENT_POST_FAILURE';

export const EVENT_LIST = 'EVENT_LIST';
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
export const EVENT_LIST_FAILURE = 'EVENT_LIST_FAILURE';

export const EVENT_EDIT = 'EVENT_EDIT';
export const EVENT_EDIT_SUCCESS = 'EVENT_EDIT_SUCCESS';
export const EVENT_EDIT_FAILURE = 'EVENT_EDIT_FAILURE';

export const EVENT_REMOVE = 'EVENT_REMOVE';
export const EVENT_REMOVE_SUCCESS = 'EVENT_REMOVE_SUCCESS';
export const EVENT_REMOVE_FAILURE = 'EVENT_REMOVE_FAILURE';

/* NOTIFICATION */
export const CLOSE_NOTIF = 'CLOSE_NOTIF';
export const OPEN_NOTIF = 'OPEN_NOTIF';

/* CALENDAR */
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_MONTH = 'UPDATE_MONTH';
