/* AUTHENTICATION */

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

/* DORM */
export const DORM_LIST = 'DORM_LIST';
export const DORM_LIST_SUCCESS = 'DORM_LIST_SUCCESS';
export const DORM_LIST_FAILURE = 'DORM_LIST_FAILURE';

export const ROOM_LIST = 'ROOM_LIST';
export const ROOM_LIST_SUCCESS = 'ROOM_LIST_SUCCESS';
export const ROOM_LIST_FAILURE = 'ROOM_LIST_FAILURE';

export const GET_ROOM = 'GET_ROOM';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOM_FAILURE = 'GET_ROOM_FAILURE';

export const COMMENT_EDIT = 'COMMENT_EDIT';
export const COMMENT_EDIT_SUCCESS = 'COMMENT_EDIT_SUCCESS';
export const COMMENT_EDIT_FAILURE = 'COMMENT_EDIT_FAILURE';

export const COMMENT_POST = 'COMMENT_POST';
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAILURE = 'COMMENT_POST_FAILURE';

export const COMMENT_REMOVE = 'COMMENT_REMOVE';
export const COMMENT_REMOVE_SUCCESS = 'COMMENT_REMOVE_SUCCESS';
export const COMMENT_REMOVE_FAILURE = 'COMMENT_REMOVE_FAILURE';

/* PROFILE */
export const GET_PREF = 'GET_PREF';
export const GET_PREF_SUCCESS = 'GET_PREF_SUCCESS';
export const GET_PREF_FAILURE = 'GET_PREF_FAILURE';

export const EDIT_PREF = 'EDIT_PREF';
export const EDIT_PREF_SUCCESS = 'EDIT_PREF_SUCCESS';
export const EDIT_PREF_FAILURE = 'EDIT_PREF_FAILURE';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const MOVE_IN_ROOM = 'MOVE_IN_ROOM';
export const MOVE_IN_ROOM_SUCCESS = 'MOVE_IN_ROOM_SUCCESS';
export const MOVE_IN_ROOM_FAILURE = 'MOVE_IN_ROOM_FAILURE';

export const MOVE_OUT_ROOM = 'MOVE_OUT_ROOM';

/* NOTIFICATION */
export const CLOSE_NOTIF = 'CLOSE_NOTIF';
export const OPEN_NOTIF = 'OPEN_NOTIF';
